### ISSUE TITLE
Fail to run because importing error

### ISSUE THREAD

**Issue by tobegit3hub** [DanielSlater/AlphaToe#1]
The document is kind of wrong and we fail to run with `python ./scripts/policy_gradient.py`.

The error log looks like this.

![screen shot 2016-10-26 at 19 13 03](https://cloud.githubusercontent.com/assets/2715000/19724007/7cb57aba-9bb0-11e6-82ba-47c88b2b03d6.png)

Please make sure the import path is right.

**Comment by DanielSlaterSK** [comment]
Hi @tobegit3hub 
Thanks for getting in touch. I've just tried running the command "python ./scripts/policy_gradient.py" from the root directory of the project and it works after doing a fresh git clone. Is there anything else that could have gone wrong? Does the module exists in games/tic_tac_toe.py? 

I have thought about maybe moving the scripts into the root directory to avoid this kind of problem. What do you think?

**Comment by tobegit3hub** [comment]
Thanks @DanielSlaterSK for your response but I still fail to run. I'm not sure if your have "install" or do something to import this.

It would be great to move the script in root directory so that everyone can run it. Or modify the script to import the the game library in relative path.

**Comment by DanielSlater** [comment]
I've moved the scripts to the root directory, does it work for you now?

**Comment by tobegit3hub** [comment]
Thanks @DanielSlater but another error occurs.

![screen shot 2016-10-31 at 09 19 39](https://cloud.githubusercontent.com/assets/2715000/19841783/7ea60b52-9f4b-11e6-9cb2-1a09e08c888b.png)

**Comment by DanielSlater** [comment]
There will be a file current_network.p in the root directory, delete that and then re-run, also do a git pull because I've fixed some stuff.

**Comment by tobegit3hub** [comment]
Everything works like a charm now. Thanks @DanielSlater for supporting 👍

**Comment by DanielSlater** [comment]
No problem :)
